### ISSUE TITLE
Add a new class for unsorted state

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#342]
I've read #259, I still think adding an unsorted state class can reduce many line of code. I tried to add a unsorted class for `tr`, but if one columns is not configured as sortable, I have to move the unsorted class to every sortable `th` explicitly.
```
<thead>
<tr class="sortable">
  <th st-sort="col1">Sortable1</th>
  <th st-sort="col2">Sortable2</th>
  <th>Not sortable</th>
</tr>
...
```
I have to write like this
```
<thead>
<tr>
  <th class="sortable" st-sort="col1">Sortable1</th>
  <th class="sortable" st-sort="col2">Sortable2</th>
  <th>Not sortable</th>
</tr>
...
```
In current `stSort.js`, if we can add an unsort class just like `stSortDescent` and `stSortAscent`, it can save a lot HTML code. Does it make sense?

**Comment by lorenzofox3** [comment]
Or maybe you can use more appropriate css selectors http://plnkr.co/edit/LbI4Sc?p=preview

```css

th[st-sort]{
  background:grey;
}

.st-sort-ascent{
  background:yellow !important;
}

.st-sort-descent{
  background:red !important;
}
```
