### ISSUE TITLE
Always show sort icons

### ISSUE THREAD

**Issue by Seiifer** [lorenzofox3/Smart-Table#565]
Hi,
first of all, congratulations and many thanks for what you are offering us.

I am using `<st-sort>` in order to sort the columns of my table, but I would like to let the user know he can sort the columns.

Indeed, until he clicks on the `<th>Column Title</th>` There is nothing indicating the user he can sort the data in the table's columns.

So what I'm trying to achieve is to have by default both icons used in the following  css :
```css
.st-sort-ascent:before{
    content: '\25B2';
}

.st-sort-descent:before{
    content: '\25BC';
}
```

but in a gray (disabled) color in order to let the user know there is no sorting active.

This would look like this when no sort is active :  ![unactive](http://arts-crafts-publishing.com/images/components/arrow-sort.png), but preferably in a gray color to point there is no active sort at the moment.

And after a sort is applied, we could either keep the current icons or use somethink like this : ![active](http://www4.infoprintsolutionscompany.com/help/topic/com.infoprint.rpde.linux.base/graphics/sort_up_2012a.png).

How could I implement something like this ?

Regards,
Seifer

**Comment by lorenzofox3** [comment]
you can apply specific style to sortable columns using the specific css selector 
```css
th[st-sort]{
 // I let your creative and artistic mind do wonders here :) 

}
```

**Comment by Seiifer** [comment]
As a first draft, to test it I tried the following :
th[st-sort]{
    content: '\25B2';
    background-color: red;
}

But it didn't seem to be applied.
I'm probably missing something there.

**Comment by lorenzofox3** [comment]
depends if you have other rules defined for th in your stylesheet, in which order you define them etc. 

But this is more related to css, not to smart-table, you'll find plenty of documentation online :)

**Comment by lorenzofox3** [comment]
example http://plnkr.co/edit/QJgEPn?p=preview

**Comment by Seiifer** [comment]
In the end, it gives something like this :
```css
/* Sortable indicator icon */
th[st-sort]:not(.st-sort-ascent):not(.st-sort-descent):before {
    content: url('http://report.ashrae.org/Certification/Content/Images/sort-arrows.gif') !important;
}
```

That's not ideal because it relies on an image, but I don't think there is any html entity for a double arrow, so this will do for now.

**Comment by Seiifer** [comment]
Actually, if you are using `font-awesome` in your project, you can do :
```css
/* Sortable indicator icon */
th[st-sort]:not(.st-sort-ascent):not(.st-sort-descent):before {
    font-family: FontAwesome;
    content: '\f0dc';
    display: inline-block;
    padding-right: 3px;
    vertical-align: middle;
}
```

This should do it !
