### ISSUE TITLE
Different icon for sorting ascending and descending

### ISSUE THREAD

**Issue by SushantKadam008** [lorenzofox3/Smart-Table#620]
Hi,
I want to change the default sort icon in smart table.
Is it possible to do so ? 

Please refer to the attached image.

![smarttablesortscenario](https://cloud.githubusercontent.com/assets/7605326/12848065/cbc52ae2-cc17-11e5-9972-358efe4a1129.PNG)

**Comment by lorenzofox3** [comment]
Hello, 

please refer to the already open issues (and by now closed) and the documentation website ...

Thanks

**Comment by SushantKadam008** [comment]
Could you please tell me which issue to check.
I did check the documentation as well. But when I make changes to the default class attached to the header it changes my header as well.

**Comment by lorenzofox3** [comment]
<img width="1428" alt="screen shot 2016-02-05 at 21 07 39" src="https://cloud.githubusercontent.com/assets/2402022/12848451/9b78dc14-cc4c-11e5-9a23-a1fe0f917f0a.png">

or 

```Markup
<th st-sort="foo"><i></i>foo</th>
```
```Css
th[st-sort] i {
    background-image: url('sortable column')
}

th[st-sort].st-sort-ascent i {
    background-image: url('ascending column')
}
```

etc
